# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

# Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.


In [163]:
import numpy as np

data = np.loadtxt('data\minutes_n_ingredients.csv', dtype='int32', delimiter=',', skiprows=1)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [164]:
print(np.mean(data, axis=0)[1], np.mean(data, axis=0)[2])
print(np.min(data, axis=0)[1], np.min(data, axis=0)[2])
print(np.max(data, axis=0)[1], np.max(data, axis=0)[2])
print(np.median(data, axis=0)[1], np.median(data, axis=0)[2])

21601.00169 9.05528
0 1
2147483647 39
40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [165]:
quant = np.quantile(data[:,1], q=0.75)
lim = data[:,1] <= quant

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [166]:
print(np.sum(data[:,1]==0))
data[:,1][data[:,1]==0]=1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [167]:
print(len(np.unique(data, axis=1)))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [181]:
print(len(np.unique(data[:,2])))
print(np.unique(data[:,2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [180]:
changed_data = data[data[:,2] <= 5]

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [182]:
print(np.max(data[:,2]/data[:,1]))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [183]:
print(np.mean(data[data[:,1].argsort()][::-1][0:100][:,2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [184]:
print(data[np.random.randint(data.shape[0], size=10), :])

[[343611     25      7]
 [226621     55      6]
 [249358     55      9]
 [413298    150      7]
 [338646    360      9]
 [109570    100     10]
 [427041     30      9]
 [231677     30     10]
 [334262     40     15]
 [128373     20      6]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [185]:
print(len(data[data[:,2] < np.mean(data[:,2])]) / len(data[:,2]) * 100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [186]:
new_data = np.c_[data, (data[:, 1] < 21) & (data[:, 2] < 6)]

13. Выведите процент "простых" рецептов в датасете

In [187]:
simple_count = new_data[new_data[:,3] == 1].shape[0]
all_count = new_data.shape[0]
print(simple_count*100/all_count)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [188]:
short_arr = new_data[new_data[:,1] < 10]
arr = new_data[(new_data[:,1] >= 10) & (new_data[:,1] < 20)]
long_arr = new_data[20 <= new_data[:,1]]

crop_value = np.min([short_arr.shape[0], arr.shape[0], long_arr.shape[0]])

print(np.array([short_arr[:crop_value], arr[:crop_value], long_arr[:crop_value]]))

[[[ 67660      5      6      0]
  [366174      7      9      0]
  [204134      5      3      1]
  ...
  [420725      5      3      1]
  [  4747      1      9      0]
  [370915      5      4      1]]

 [[ 94746     10      6      0]
  [ 33941     18      9      0]
  [446597     15      5      1]
  ...
  [  9831     15      7      0]
  [335859     12     14      0]
  [256812     10      3      1]]

 [[127244     60     16      0]
  [ 23891     25      7      0]
  [157911     60     14      0]
  ...
  [168901     25      7      0]
  [392339     35     13      0]
  [206732     45     10      0]]]
